import{a as u,i as c,S as m}from"./assets/vendor-C4-ZuMk8.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function a(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(t){if(t.ep)return;t.ep=!0;const r=a(t);fetch(t.href,r)}})();const h="https://pixabay.com/api/",b="36431598-58be2282cdfdc5fc3df430395";async function L(e,o=1,a=15){const n=`${h}?key=${b}&q=${e}&image_type=photo&orientation=horizontal&safesearch=true&page=${o}&per_page=${a}`;return(await u.get(n)).data}function w(e){const o=document.querySelector(".gallery"),a=e.map(n=>I(n)).join("");o.insertAdjacentHTML("beforeend",a)}function I({webformatURL:e,largeImageURL:o,tags:a,likes:n,views:t,comments:r,downloads:s}){return`
    <a class="gallery-item" href="${o}">
      <div class="gallery-card">
        <img src="${e}" alt="${a}" loading="lazy" class="gallery-image"/>
        <div class="gallery-info">
          <p class="gallery-info-item"><span class="gallery-info-bold">Likes</span> <br />${n}</p>
          <p class="gallery-info-item"><span class="gallery-info-bold">Views</span> <br />${t}</p>
          <p class="gallery-info-item"><span class="gallery-info-bold">Comments</span> <br />${r}</p>
          <p class="gallery-info-item"><span class="gallery-info-bold">Downloads</span> <br />${s}</p>
        </div>
      </div>
    </a>
  `}let d,y="",l=1;const g=15,$=document.querySelector("#search-form"),i=document.getElementById("load-more"),f=document.querySelector(".gallery");$.addEventListener("submit",v);i.addEventListener("click",P);async function v(e){if(e.preventDefault(),y=e.target.elements.searchQuery.value.trim(),l=1,!y){c.warning({title:"Warning",message:"Please enter a search query.",position:"topRight"});return}E(),i.style.display="none",await p()}async function p(){R();try{const{hits:e,totalHits:o}=await L(y,l,g);if(e.length===0){c.error({title:"Error",message:"Sorry, no images match your search query. Please try again.",position:"topRight"});return}w(e),S(),l>1&&q(),l*g<o?i.style.display="block":(c.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),i.style.display="none")}catch(e){c.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(e)}finally{B()}}async function P(){l+=1,await p()}function E(){f.innerHTML=""}function S(){d&&d.destroy(),d=new m(".gallery-item",{captionsData:"alt",captionDelay:250})}function q(){const{height:e}=f.firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}function R(){const e=document.getElementById("loading-indicator");e.style.display="block",i.style.display="none"}function B(){const e=document.getElementById("loading-indicator");e.style.display="none",i.style.display="block"}
//# sourceMappingURL=index.js.map
